name: Deploy Go App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: false

      - name: Build Go app with version
        run: |
          go mod tidy
          VERSION=$(date +'%Y%m%d%H%M%S')
          go build -o app_${VERSION} main.go
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Git tag for version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${APP_VERSION}" -m "Release version v${APP_VERSION}"
          git push origin "v${APP_VERSION}"
