name: Deploy Go App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: false

      - name: Build Go app
        run: |
          go mod tidy
          VERSION=$(date +'%Y%m%d%H%M%S')
          go build -o app_${VERSION} main.go
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ccprj58@10.24.2.17 "echo '✅ SSH key authentication works'"

      - name: Deploy to server (with version)
        run: |
          rsync -avz \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "*.log" \
            --exclude "README.md" \
            --exclude "go/pkg/" \
            --exclude "go/bin/" \
            --exclude "go/src/" \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./app_${APP_VERSION} ccprj58@10.24.2.17:/var/www/html/go_projects/HRMODULE/hrnew/HR/
